### ISSUE TITLE
Not Proxying Connection

### ISSUE THREAD

**Issue by shatteredeagle** [tsaibermelon/gg-struggle#16]
Heya,

Haven't had much luck getting this going, just sits and doesn't proxy the connection? Everything seems to be installed correct, certs in the correct store, and hosts pointing to the current IP of the server. 

```[2021-07-20T14:54:09.085] [INFO] default - [PROXY] Logging to C:\Users\shatt\AppData\Local\Temp/gg-struggle/all.log
[2021-07-20T14:54:09.086] [INFO] default - [PROXY] Using pfx file ./gg-struggle-cert.pfx
[2021-07-20T14:54:09.087] [INFO] default - [DB] Loading entries C:\Users\shatt\AppData\Local\Temp/gg-struggle/gg-struggle.db
[2021-07-20T14:54:09.105] [INFO] default - [PROXY] Listening on 443
[2021-07-20T14:54:09.106] [INFO] default -

**Comment by shatteredeagle** [comment]
Upgraded to 2.0, exact same issue. No errors, running fine, just cant connect to servers in game. Updated hosts file to whatever the latest IP is of the servers.

**Comment by cybermelons** [comment]
For 2.0, there only needs to be the hosts entry `127.0.0.1 ggst-game.guiltygear.com`. The latest server ip addresses are dynamically resolved at runtime

**Comment by shatteredeagle** [comment]
So this is all that's in my hosts now:

``` #GG-Struggle
127.0.0.1	ggst-game.guiltygear.com
```

Still getting No Connection and no output to the terminal, looks like its sitting waiting for connections but never gets any? 

edit: ~Wondering if its Windows Firewall causing issues?~ Disabled, same issue

**Comment by cybermelons** [comment]
Do you have multiple network devices? Just a guess but maybe it's running on a specific network interface

**Comment by shatteredeagle** [comment]
![image](https://user-images.githubusercontent.com/26069301/127067288-c980f1af-89bf-4cd6-a4ff-9e8463be4bce.png)
I uhhhh, may have a few....

Disabled them all and sans actual NIC and its workin! THANK YOU!!!

**Comment by cybermelons** [comment]
Nice! closing because solution above
